---
azure:
  function_app_name: psp-data-viewer-api
  resource_group: pspdataviewer
  storage_account: pspdataviewer
  share_name: psp-data-viewer3d1877
colors:
  accent: '#8e6f3e'
  background: '#1D1D1D'
  background_light: '#6f727b'
  primary: '#ddb945'
  primary_dark: '#daaa00'
firebase:
  apiKey: AIzaSyDzZWBXQ5L9N92GRNUNGMse8AeUvbwFFyI
  appId: 1:267504321387:web:3c5b9c2a1ec15ff452822e
  app_check_provider_token: ''
  authDomain: dataviewer-space.firebaseapp.com
  measurementId: G-WRP7BXPKHK
  messagingSenderId: '267504321387'
  projectId: dataviewer-space
  storageBucket: dataviewer-space.firebasestorage.app
  webapp_site: dataviewer-staging-1
  databaseID: staging-1
naming:
  name_long: 'Staging: Dev Dataviewer'
  name_short: Dev Dataviewer
  page_title: "Staging"
  slug: dev
urls:
  admin_dashboard_url: https://admin.dataviewer.space/dev
  api_base_url: https://psp-data-viewer-api.azurewebsites.net
  docs_url: https://docs.dataviewer.space
  github_url: https://github.com/rajanphadnis/psp-data-viewer
  update_test_metadata_url: https://updatetestmetadata-w547ikcrwa-uc.a.run.app
stripe:
  customerID: cus_Rp9DJxykmqZ3wU