name: Deploy Instance

on:
  workflow_dispatch:
    inputs:
      docID:
        required: true
      id:
        required: false
        description: "run identifier"

jobs:
  id:
    runs-on: ubuntu-latest

    steps:
      - name: ${{github.event.inputs.id}}
        run: echo "ready"
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Create SA JSON
        run: echo '${{ secrets.GOOGLECLOUDSA_GITHUBACCESS }}' > ./build_tools/GoogleCloudSA_GitHubAccess.json
      - name: list
        run: ls -lR
      - name: Run Script
        run: bun install && bun run ts ${{ github.event.inputs.docID }}
