name: Deploy Instance

on:
  workflow_dispatch:
    inputs:
      docID:
        required: true
      slug:
        required: true
      cusID:
        required: true
      id:
        required: false
        description: "run identifier"

permissions:
  actions: write
  contents: write

jobs:
  firebaseAndStripe:
    runs-on: ubuntu-latest
    steps:
      - name: ${{github.event.inputs.id}}
        run: echo "ready"
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Create SA JSON
        run: echo '${{ secrets.GOOGLECLOUDSA_GITHUBACCESS }}' > ./build_tools/GoogleCloudSA_GitHubAccess.json
      - name: Run Script
        run: bun install && bun run new-customer-firebase-stripe ${{ github.event.inputs.docID }}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: New Instance Provisioned

  azure:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        scope: "subscription"
        template: ./build_tools/customer_config/deploy_bicep/main.bicep
        parameters: 'slug=${{github.event.inputs.slug}} customerID=${{github.event.inputs.cusID}} stripeKey=${{ secrets.STRIPE_SECRET_KEY }}'
        failOnStdErr: false

  finish:
    runs-on: ubuntu-latest
    needs: [firebaseAndStripe, azure]
    steps:
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Create SA JSON
        run: echo '${{ secrets.GOOGLECLOUDSA_GITHUBACCESS }}' > ./build_tools/GoogleCloudSA_GitHubAccess.json
      - name: Run Script
        run: bun install && bun run new-customer-config ${{ github.event.inputs.docID }}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: New Instance Provisioned