name: Deploy Instance

on:
  workflow_dispatch:
    inputs:
      docID:
        required: true
      id:
        required: false
        description: "run identifier"
permissions:
  actions: write
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ${{github.event.inputs.id}}
        run: echo "ready"
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Create SA JSON
        run: echo '${{ secrets.GOOGLECLOUDSA_GITHUBACCESS }}' > ./build_tools/GoogleCloudSA_GitHubAccess.json
      - name: Run Script
        run: bun install && bun run new-customer ${{ github.event.inputs.docID }}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: New Instance Provisioned
