name: Deploy Instance

on:
  workflow_dispatch:
    inputs:
      docID:
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Create SA JSON
        run: echo "${{ secrets.GOOGLECLOUDSA_GITHUBACCESS }}" > ./build_tools/GoogleCloudSA_GitHubAccess.json
      - name: Run Script
        run: bun install && bun run ts ${{ github.event.inputs.docID }}
