name: "[CD:Production] Build and Release"
on:
  push:
    tags:
      - "v*.*.*"

env:
  PYTHON_VERSION: "3.11"

permissions:
  contents: write
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Web App Unit Tests
        run: cd webapp_v2 && bun install && bun run test
      - name: Admin App Unit Tests
        run: cd admin_v2 && bun install && bun run test
      - name: Customer Config Validity Checks
        run: bun install && bun run config_check
  changelog-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Tag/Release search
        run: echo "GHA_V_COUNTER=$(grep ${{ github.ref_name }} CHANGELOG.md | wc -l)" >> "$GITHUB_ENV"
        shell: bash
      - name: Tag Output
        run: echo "env.GHA_V_COUNTER = ${{ env.GHA_V_COUNTER }}"
        shell: bash
      - name: "If changelog isn't updated, delete the release and tag"
        uses: dev-drprasad/delete-tag-and-release@v1.0
        if: env.GHA_V_COUNTER == '0'
        with:
          tag_name: ${{ github.ref_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_release: true
      - name: Find '${{ github.ref_name }}' in CHANGELOG.md
        if: env.GHA_V_COUNTER == '0'
        uses: actions/github-script@v2.1.0
        with:
          script: |
            core.setFailed('CHANGELOG.md not updated to include new release notes for ${{ github.ref_name }}!')
  version-check-webapp:
    runs-on: ubuntu-latest
    outputs:
      version-code: ${{ steps.version-code-gen.outputs.GHA_VERSION_CODE }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up new test tag
        run: |
          TAGNAME=${{ github.ref_name }}
          NEW_NAME="${TAGNAME//v/}"
          echo GHA_NEW_TAG_NAME_WEBAPP=$NEW_NAME >> "$GITHUB_ENV"
      - name: Tag/Release search
        run: echo "GHA_V_COUNTER_WEBAPP=$(grep '${{ format('"version"{0}', ':') }} "${{ env.GHA_NEW_TAG_NAME_WEBAPP }}"' webapp_v2/package.json | wc -l)" >> "$GITHUB_ENV"
        shell: bash
      - name: Tag Output
        run: |
          echo "env.GHA_V_COUNTER_WEBAPP = ${{ env.GHA_V_COUNTER_WEBAPP }}"
          echo "env.GHA_NEW_TAG_NAME_WEBAPP = ${{ env.GHA_NEW_TAG_NAME_WEBAPP }}"
        shell: bash
      - name: "If pubspec isn't updated, delete the release and tag"
        uses: dev-drprasad/delete-tag-and-release@v1.0
        if: env.GHA_V_COUNTER_WEBAPP == '0'
        with:
          tag_name: ${{ github.ref_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_release: true
      - name: Find '${{ github.ref_name }}' in package.json
        if: env.GHA_V_COUNTER_WEBAPP == '0'
        uses: actions/github-script@v2.1.0
        with:
          script: |
            core.setFailed('webapp_v2/package.json not updated to new version ${{ env.GHA_NEW_TAG_NAME_WEBAPP }}!')
  version-check-admin:
    runs-on: ubuntu-latest
    outputs:
      version-code: ${{ steps.version-code-gen.outputs.GHA_VERSION_CODE }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up new test tag
        run: |
          TAGNAME=${{ github.ref_name }}
          NEW_NAME="${TAGNAME//v/}"
          echo GHA_NEW_TAG_NAME_ADMIN=$NEW_NAME >> "$GITHUB_ENV"
      - name: Tag/Release search
        run: echo "GHA_V_COUNTER_ADMIN=$(grep '${{ format('"version"{0}', ':') }} "${{ env.GHA_NEW_TAG_NAME_ADMIN }}"' admin_v2/package.json | wc -l)" >> "$GITHUB_ENV"
        shell: bash
      - name: Tag Output
        run: |
          echo "env.GHA_V_COUNTER_ADMIN = ${{ env.GHA_V_COUNTER_ADMIN }}"
          echo "env.GHA_NEW_TAG_NAME_ADMIN = ${{ env.GHA_NEW_TAG_NAME_ADMIN }}"
        shell: bash
      - name: "If pubspec isn't updated, delete the release and tag"
        uses: dev-drprasad/delete-tag-and-release@v1.0
        if: env.GHA_V_COUNTER_ADMIN == '0'
        with:
          tag_name: ${{ github.ref_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_release: true
      - name: Find '${{ github.ref_name }}' in package.json
        if: env.GHA_V_COUNTER_ADMIN == '0'
        uses: actions/github-script@v2.1.0
        with:
          script: |
            core.setFailed('admin_v2/package.json not updated to new version ${{ env.GHA_NEW_TAG_NAME_ADMIN }}!')
  version-check-docs:
    runs-on: ubuntu-latest
    outputs:
      version-code: ${{ steps.version-code-gen.outputs.GHA_VERSION_CODE }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up new test tag
        run: |
          TAGNAME=${{ github.ref_name }}
          NEW_NAME="${TAGNAME//v/}"
          echo GHA_NEW_TAG_NAME_ADMIN=$NEW_NAME >> "$GITHUB_ENV"
      - name: Tag/Release search
        run: echo "GHA_V_COUNTER_ADMIN=$(grep '${{ format('"version"{0}', ':') }} "${{ env.GHA_NEW_TAG_NAME_ADMIN }}"' docs/package.json | wc -l)" >> "$GITHUB_ENV"
        shell: bash
      - name: Tag Output
        run: |
          echo "env.GHA_V_COUNTER_ADMIN = ${{ env.GHA_V_COUNTER_ADMIN }}"
          echo "env.GHA_NEW_TAG_NAME_ADMIN = ${{ env.GHA_NEW_TAG_NAME_ADMIN }}"
        shell: bash
      - name: "If package.json isn't updated, delete the release and tag"
        uses: dev-drprasad/delete-tag-and-release@v1.0
        if: env.GHA_V_COUNTER_ADMIN == '0'
        with:
          tag_name: ${{ github.ref_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_release: true
      - name: Find '${{ github.ref_name }}' in package.json
        if: env.GHA_V_COUNTER_ADMIN == '0'
        uses: actions/github-script@v2.1.0
        with:
          script: |
            core.setFailed('docs/package.json not updated to new version ${{ env.GHA_NEW_TAG_NAME_ADMIN }}!')
  version-check-mission:
    runs-on: ubuntu-latest
    outputs:
      version-code: ${{ steps.version-code-gen.outputs.GHA_VERSION_CODE }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up new test tag
        run: |
          TAGNAME=${{ github.ref_name }}
          NEW_NAME="${TAGNAME//v/}"
          echo GHA_NEW_TAG_NAME_MISSION=$NEW_NAME >> "$GITHUB_ENV"
      - name: Tag/Release search
        run: echo "GHA_V_COUNTER_MISSION=$(grep '${{ format('"version"{0}', ':') }} "${{ env.GHA_NEW_TAG_NAME_MISSION }}"' mission/package.json | wc -l)" >> "$GITHUB_ENV"
        shell: bash
      - name: Tag Output
        run: |
          echo "env.GHA_V_COUNTER_MISSION = ${{ env.GHA_V_COUNTER_MISSION }}"
          echo "env.GHA_NEW_TAG_NAME_MISSION = ${{ env.GHA_NEW_TAG_NAME_MISSION }}"
        shell: bash
      - name: "If pubspec isn't updated, delete the release and tag"
        uses: dev-drprasad/delete-tag-and-release@v1.0
        if: env.GHA_V_COUNTER_MISSION == '0'
        with:
          tag_name: ${{ github.ref_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_release: true
      - name: Find '${{ github.ref_name }}' in package.json
        if: env.GHA_V_COUNTER_MISSION == '0'
        uses: actions/github-script@v2.1.0
        with:
          script: |
            core.setFailed('mission/package.json not updated to new version ${{ env.GHA_NEW_TAG_NAME_MISSION }}!')

  generate_matrix:
    needs:
      [
        unit-tests,
        changelog-check,
        version-check-webapp,
        version-check-admin,
        version-check-docs,
        version-check-mission,
      ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get list of YAML files
        id: list-matrix
        run: find ./customer_configs/ -type f -name "*.yml" | sed 's/\.\/customer_configs\///' | sed 's/.*/"&"/' | awk '{print}' ORS=', ' | rev | cut -c 3- | rev | sed 's/.*/configs={\"config\":[&]}/' >> $GITHUB_OUTPUT
    outputs:
      configs: ${{ steps.list-matrix.outputs.configs }}

  build:
    runs-on: ubuntu-latest
    needs: generate_matrix
    strategy:
      matrix: ${{ fromJson(needs.generate_matrix.outputs.configs) }}
    # strategy:
    #   matrix:
    #     config: ["dev.yml"]
    name: Build & Deploy Webapp from ${{ matrix.config }}
    environment:
      name: "Production"
    steps:
      - uses: actions/checkout@v4
      - name: Read Config File
        uses: pietrobolcato/action-read-yaml@1.1.0
        id: get_config
        with:
          config: ${{ github.workspace }}/customer_configs/${{ matrix.config }}
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Build Web App
        working-directory: ./webapp_v2
        run: bun install && bun run prod ${{ matrix.config }}
      - name: Release Web App
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DATAVIEWER_SPACE }}
          channelId: live
          projectId: dataviewer-space
          target: webapp

  build-formatter:
    runs-on: windows-latest
    needs:
      [
        unit-tests,
        changelog-check,
        version-check-webapp,
        version-check-admin,
        version-check-docs,
        version-check-mission,
      ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure WinRAR is installed
        run: |
          $winrarPath = "${env:ProgramFiles}\WinRAR\WinRAR.exe"
          if (-Not (Test-Path $winrarPath)) {
            Write-Host "WinRAR not found. Downloading and installing..."
            Invoke-WebRequest -Uri "https://www.win-rar.com/fileadmin/winrar-versions/winrar-x64-701.exe" -OutFile "winrar.exe"
            Start-Process -FilePath ".\winrar.exe" -ArgumentList "/S" -NoNewWindow -Wait
          } else {
            Write-Host "WinRAR is already installed."
          }
        shell: pwsh

      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          profile: minimal

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "formatter -> target"

      - uses: cargo-bins/cargo-binstall@main

      - name: Install Dioxus
        run: cargo binstall dioxus-cli --force
        shell: cmd

      - name: Build App
        run: cd formatter && dx bundle --platform windows --features bundle
        shell: cmd

      - name: Create SFX Archive
        run: cd build_tools/ && formatter.bat
        shell: cmd

      - name: Upload SFX Archive
        uses: actions/upload-artifact@v4
        with:
          name: sfx-archive
          path: ./formatter/dataviewer.exe
          compression-level: 0 # no compression
          retention-days: 1

  deploy-site:
    runs-on: ubuntu-latest
    needs: build-formatter
    name: Build & Deploy Website
    environment:
      name: "Production"
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Download EXE
        uses: actions/download-artifact@v4
        with:
          name: sfx-archive
          path: website/src/assets
      - name: Build Web App
        working-directory: ./website
        run: bun install && bun run build
      - name: Release Web App
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DATAVIEWER_SPACE }}
          channelId: live
          projectId: dataviewer-space
          target: website

  deploy-admin:
    runs-on: ubuntu-latest
    needs: generate_matrix
    name: Build & Deploy Admin Console
    environment:
      name: "Production"
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Build Web App
        working-directory: ./admin_v2
        run: bun install && bun run build
      - name: Release Web App
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_DATAVIEWER_SPACE }}
          channelId: live
          projectId: dataviewer-space
          target: admin

  github-release:
    runs-on: ubuntu-latest
    needs: [build, build-formatter, deploy-site, deploy-admin]
    environment:
      name: "Production"
    steps:
      - uses: actions/checkout@v4
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: sfx-archive
      - name: trim changelog to most recent change entry
        run: "{ awk '/^## /{count++} count==2{exit} 1' CHANGELOG.md; echo '...'; } >> trimmed_change.md"
      - name: Update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          append_body: true
          generate_release_notes: true
          body_path: ${{ github.workspace }}/trimmed_change.md
          files: dataviewer.exe
